---
- name: restart systemd-zram
  ansible.builtin.systemd:
    name: systemd-zram-setup@zram0.service
    state: restarted
    daemon_reload: true

- name: restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted

- name: Restart zramswap
  ansible.builtin.systemd:
    name: zramswap
    state: restarted

- name: restart chrony service
  ansible.builtin.systemd:
    name: "{{ chrony_service }}"
    state: restarted

- name: Restart SSH service
  ansible.builtin.systemd:
    name: "{{ ssh_service_name }}"
    state: restarted

- name: Restart auditd
  ansible.builtin.command: service auditd restart
  failed_when: false

- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: restart networkmanager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted

- name: reload ufw
  ansible.builtin.systemd:
    name: ufw
    state: restarted

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: restart falco service
  ansible.builtin.service:
    name: falco
    state: restarted

- name: restart nexus
  ansible.builtin.systemd:
    name: nexus
    state: restarted